# Generated by Django 2.2.1 on 2019-07-09 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReactGameService', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attempt',
            old_name='organisation_id',
            new_name='organisation',
        ),
        migrations.RenameField(
            model_name='attempt',
            old_name='test_id',
            new_name='test',
        ),
        migrations.RenameField(
            model_name='attempt',
            old_name='testee_id',
            new_name='testee',
        ),
    ]
