# Generated by Django 2.2.1 on 2019-07-09 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReactGameService', '0002_auto_20190709_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testee',
            old_name='username',
            new_name='react_username',
        ),
    ]
