# Generated by Django 2.2.1 on 2019-07-16 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReactGameService', '0003_auto_20190709_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='type',
            new_name='status_type',
        ),
    ]
