# Generated by Django 2.2.1 on 2019-07-16 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReactGameService', '0004_auto_20190715_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='created_at',
            field=models.DateTimeField(editable=False),
        ),
    ]
