# Generated by Django 2.2.1 on 2019-07-19 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReactGameService', '0006_auto_20190719_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
